/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class gameBackgroundUI extends Laya.Scene {
		public background:Laya.Sprite;
		public unhitMole:Laya.Sprite;
		public mask1:Laya.Sprite;
		public hitMole:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("gameBackground");
        }
    }
    REG("ui.gameBackgroundUI",gameBackgroundUI);
}